apiVersion: v1
kind: Secret
metadata:
  name: hayasui-secret
type: Opaque
stringData:
  HYS_TOKEN: "discord-token"
  HYS_PREFIX: ">"
  HYS_API_HOST: "http://localhost:8006"
  HYS_LINK_HOST: "http://localhost:3000"
  HYS_REDIS_ADDRESS: "localhost:6379"
  HYS_REDIS_PASSWORD: ""
  HYS_REDIS_TIME: "86400"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hayasui-deployment
  labels:
    app: hayasui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hayasui
  template:
    metadata:
      generateName: hayasui-pod-
      labels:
        app: hayasui
    spec:
      containers:
        - name: hayasui
          image: hayasui:latest
          imagePullPolicy: IfNotPresent
          command: ["/hayasui"]
          args: ["bot"]
          envFrom:
            - secretRef:
                name: hayasui-secret
