name: import terraform

on: workflow_dispatch

jobs:
  import_terraform:
    name: Import Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment/terraform
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Auth gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup Terraform Variables
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          gcp_project_id           = "${{ secrets.GCP_PROJECT_ID }}"
          gcp_region               = "${{ secrets.GCP_REGION }}"
          gke_cluster_name         = "${{ secrets.GKE_CLUSTER_NAME }}"
          gke_location             = "${{ secrets.GKE_LOCATION }}"
          gke_pool_name            = "${{ secrets.GKE_POOL_NAME }}"
          gke_node_preemptible     = "${{ secrets.GKE_NODE_PREEMPTIBLE }}"
          gke_node_machine_type    = "${{ secrets.GKE_NODE_MACHINE_TYPE }}"
          gke_node_disk_size_gb    = "${{ secrets.GKE_NODE_DISK_SIZE_GB }}"
          gcr_image_name           = "${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/hayasui:${{ needs.publish_image.outputs.img_tag }}"
          gke_deployment_name      = "${{ secrets.GKE_DEPLOYMENT_NAME }}"
          hys_discord_token        = "${{ secrets.HYS_DISCORD_TOKEN }}"
          hys_discord_prefix       = "${{ secrets.HYS_DISCORD_PREFIX }}"
          hys_cache_dialect        = "${{ secrets.HYS_CACHE_DIALECT }}"
          hys_cache_address        = "${{ secrets.HYS_CACHE_ADDRESS }}"
          hys_cache_password       = "${{ secrets.HYS_CACHE_PASSWORD }}"
          hys_cache_time           = "${{ secrets.HYS_CACHE_TIME }}"
          hys_log_level            = "${{ secrets.HYS_LOG_LEVEL }}"
          hys_log_json             = "${{ secrets.HYS_LOG_JSON }}"
          hys_newrelic_license_key = "${{ secrets.HYS_NEWRELIC_LICENSE_KEY }}"
          EOF
      - name: Init Terraform
        run: terraform init -backend-config "bucket=${{ secrets.GCS_BUCKET }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Import Terraform
        run: |
          terraform import -input=false google_container_cluster.cluster ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_LOCATION }}/${{ secrets.GKE_CLUSTER_NAME }}
          terraform import -input=false google_container_node_pool.pool ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_LOCATION }}/${{ secrets.GKE_CLUSTER_NAME }}/${{ secrets.GKE_POOL_NAME }}
          terraform import -input=false kubernetes_deployment.bot default/${{ secrets.GKE_DEPLOYMENT_NAME }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}